services:
  nats-server:
    image: nats:2.11.8-alpine3.22
    ports:
      - "14222:4222"
      - "16222:6222"
      - "18222:8222"
  minio:
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
