initscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.cyclonedx.bom:org.cyclonedx.bom.gradle.plugin:3.4.1'
    }
}

allprojects {
    // output dir: build/reports/cyclonedx-direct/bom.json
    apply plugin: org.cyclonedx.gradle.CyclonedxPlugin
}
